jiangye/jiangye/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings

from jiangyeapp import views
from django.conf.urls.static import static


from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',views.register,name='register'),
    #www.jiangye.com/index/  ->函数
    #注意，更新完路由信息后要重启django
    path('index', views.index),
    path('user/list/', views.user_list),
    path('user/add/', views.user_add),
    path('tpl/',views.tpl),
    path('news/',views.news),
    path('something/',views.something),
    path('login/',views.login),
    path('orm/',views.orm),

    #test
    path('info_list/',views.info_list),
    path('info/add/',views.info_add),
    path('info/delete/',views.info_delete),
    path('<year>/<int:month>/<slug:day>',views.myvariable,),
    path('index/',views.index,{'month':'2019/10/10'}),

    #jaingyetest
    #path('book/',views.book),
    #path('book/detail<book_id>',views.book_detail),
 #movieslist
    
    path('moviesList/',include(('moviesList.urls','moviesList'),namespace='moviesList')),
    path('book/',include(('jiangyebook.urls','jiangyebook'),namespace='book')),#一定要加上app名字
    # 配置媒体文件的路由地址
    re_path('media/(?P<path>.*)',serve,
       {'document_root': settings.MEDIA_ROOT}, name='media'),
       #正则表达[0-9]从0到9，{4}四位
    re_path('(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2}).html',
views.mydate)   
    
   
    


]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

jiangye/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from . import settings


from django.conf.urls.static import static


from django.views.static import serve

from jiangye.settings import MEDIA_ROOT
from django.contrib.auth.decorators import login_required
# from moviesForum import views 
from jiangyeapp import views


urlpatterns = [
    path('admin/', admin.site.urls),
    
   
    path('', views.index,name='index'),
    path('user/list/', views.user_list),
    path('user/add/', views.user_add),
    path('tpl/',views.tpl),
    path('news/',views.news),
    path('something/',views.something),
    path('login/',views.login),
    path('orm/',views.orm),
    path('bootstrap5/',views.bootstrap5),
    #test
    path('info_list/',views.info_list),
    path('show_post_user/',views.show_post_user),
    path('showpostlist_pre',views.showpostlist_pre),
    path('showpost_list',views.showpost_list),
   
    path('info/add/',views.info_add),
    path('info/delete/',views.info_delete),
    path('<year>/<int:month>/<slug:day>',views.myvariable,),
    path('index/',views.index,{'month':'2019/10/10'}),
    # path('test/',views.testjs),
    path('test/',views.youtube),
    path('test1/',views.test1),
    path('testjs/',views.testjs,name='testjs'),
    # path(r'testjs/',as_views.testjs)
    # path(r'testjs/', login_required(views.testjs.as_view()), name='order'),
    # path('login/?next=/testjs/',views.testjs),

    path('test2/',views.test1),
    path('searchmovies/',views.testjs,name='searchmovies'),
    path('superindex/',views.superindex,name='superindex'),
    path('youtube/',views.youtube,name='youtube'),
    path('post',views.publish_post,name='post'),
    path('show_post',views.show_post),
    path('quote/',views.Famous_Quotes),
    path('posts/<int:pk>/', views.detail, name='detail'),

    
    

    
    
    

    # path('test/testjs/',views.testjs),
    #jaingyetest
    #path('book/',views.book),
    #path('book/detail<book_id>',views.book_detail),
 #movieslist
    
    path('moviesList/',include(('moviesList.urls','moviesList'),namespace='moviesList')),
    path('user/',include(('user.urls','user'),namespace='user')),
    path('moviesForum/',include(('moviesForum.urls','moviesForum'),namespace='moviesForum')),

    
    # Configure the routing address of the media file
    re_path('media/(?P<path>.*)',serve,{'document_root': MEDIA_ROOT}, name='media'),
       
    re_path('(?P<year>[0-9]{4})/(?P<month>[0-9]{2})/(?P<day>[0-9]{2}).html',
views.mydate)   
    
   
    


]+static(settings.MEDIA_URL,document_root=MEDIA_ROOT)

#+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from unicodedata import name
from django.urls import path,re_path

from django.conf.urls.static import static
from django.conf import settings
from user import views

from django.views.static import serve
from django.contrib.auth import views as auth_views
#注意 urlpatterns有大写版本

app_name ='user'

urlpatterns = [

    path('',views.book),
    path('detail/<book_id>',views.book_detail),
    path('test',views.test),
    path('userimg_upload',views.userimg_upload),
    path('register/',views.register,name='register'),
    path('check_user/',views.check_user,name='check_user'),
    path('login/',views.userlogin,name='login'),
path('active/',views.user_active,name='active'),
    path('tbase/',views.base),
    path('add2watchlist',views.add2watchlist,name='add2watchlist'),
    path('<str:user_name>/', views.user, name="user"), 
    path('watchList/<str:user_name>/', views.watchList, name="watchList"), 
    
    path('logout/',views.loginoutUser,name='logout'),
    re_path('media/(?P<path>.*)',serve,{'document_root': settings.MEDIA_ROOT}, name='media'),
    re_path('media/usersImg/(?P<path>.*)',serve,{'document_root': settings.MEDIA_ROOT}, name='media'),
    


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jiangyeapp/models.py
import email
from email.policy import default
from turtle import title
from unicodedata import name
from django.db import models
from pkg_resources import require
from django.contrib.auth.models import AbstractUser
from django.contrib import auth
# Create your models here.
# MEDIA_ADDR = 'http://localhost:8000/media/'
# class userinformation(AbstractUser):
#     userid = models.AutoField(primary_key=True)
#     username = models.CharField(max_length=32,verbose_name='usersname',null=True,unique=True)#如果是charfield 必须写max_length
#     password = models.CharField(max_length=32,verbose_name='userpassword',null=True)
#     age = models.IntegerField(null=True,blank=False)
#     size = models.IntegerField(null=True,blank=False)
#     date = models.IntegerField(default=2,null=True)
#    # account=models.DecimalField(max_digits=10,decimal_places=2,default=0)#decimal保留两位小数
#     create_time = models.DateTimeField(null=True,blank=True)#添加新字段需要在sql上同步
#     email = models.CharField(max_length=32,verbose_name='email',null=True)
#     userImg = models.ImageField(upload_to='usersImg/',verbose_name=u'img',default=0)

#     def get_uesrImg_url(self):
#         return MEDIA_ADDR + str(self.uesrImg)


    
    

"""  
create table app01_userinfo(
    id bigint auto_increment primary key,
    name varchar(32),
    password varchar(64),
    age int
)""" 

# class Department(models.Model):
#     id= models.BigAutoField(verbose_name='ID自增',primary_key=True)#BigAutoField Id为自增
#     title = models.CharField(max_length=16)

# class Role(models.Model):
#     title = models.CharField(max_length=16)    

#Department.objects.create(title="giaogiao")

#UserInfo.objects.create(name="giaogiao",age=2)

jiangye/jiangyeapp/views.py
from asyncio.windows_events import NULL
from calendar import month
from contextlib import nullcontext
from email import message
from pickle import GET
from tkinter import image_types
from turtle import title
from unicodedata import name
from wsgiref.handlers import read_environ
from django.conf import settings
from django.forms import PasswordInput
from django.shortcuts import render, HttpResponse, redirect
from jiangyeapp.models import Department, UserInfo
from jiangyeapp import models
from django.core.mail import send_mail


# Create your views here.

def index(request,month):
    # return HttpResponse("welcome")
    #return render(request, "index.html",+month)错误写法
    return HttpResponse('路由之外的变量:'+month)


def user_list(request):
    return render(request, "user_list.html")


def user_add(request):
    return render(request, "user_add.html")


def tpl(request):
    name = "giao哥"
    roles = ["xijingping", "江泽民", "曾宪国"]
    user_info = {"name": "giao", "salary": 12222, "roo": "crp"}
    data_list = [
        {"name": "giao1", "salary": 12422, "roo": "crp"},
        {"name": "giao2", "salary": 2, "roo": "cr23p"},
        {"name": "giao3", "salary": 92, "roo": "cr1p"},
        {"name": "giao4", "salary": 1202, "roo": "cr00p"},

    ]
    return render(request, 'tpl.html', {"n1": name, "n2": roles, "n3": user_info, "n4": data_list}, )


def news(request):
    return render(request, 'news.html')


def something(request):
    print(request.method)  # 获取请求方式

    print(request.GET)  # 在url上传送值 明面传输

    print(request.POST)  # 在请求体上提交数据 暗

    # return HttpResponse("fanhuineirong")
    return redirect("http://www.javdb.com")


def login(request):
    if request.method == "GET":
        return render(request, "login.html")
    else:
        # 如果是post请求就获取用户提交的数据

        # print(request.POST)
        username = request.POST.get("user")
        password = request.POST.get("password")
        if username == '1' and password == "1":
            # return HttpResponse("登陆成功")
            return redirect("http://www.javbus.com")
        else:
            # return HttpResponse("登陆成功")
            return render(request, "login.html", {"error_msg": "登陆失败"})


def orm(request):
    models.Department.objects.create(title="giao12")

    models.UserInfo.objects.create(name="曾宪国", age=12, size=21)
    models.UserInfo.objects.create(name="钱其德", age=1234, size=221)
    models.UserInfo.objects.create(name="高红梅", age=122, size=216)

    # UserInfo.objects.all().delete()
    # Department.objects.all().delete()
    UserInfo.objects.filter(id=111).delete()
    # data_list = UserInfo.objects.all()
    # -=-=-=--=-------------------------
    # for obj in data_list:
    #    print(obj.id,obj.name)
    # =======================
    # data_list = UserInfo.objects.filter(name="钱其德")
    # print(data_list)
    # ---------------------------------------------更新数据
    UserInfo.objects.filter(name="giaogiao").update(password="dsa")

    return HttpResponse("火花！一给窝里给gioagiao")


def info_list(request):
    # 获取数据库种所有用户信息
    datalist = UserInfo.objects.all()

    return render(request, "info_list.html", {"data_list": datalist})


def info_add(request):
    user = request.POST.get("user")
    pwd = request.POST.get("pwd")
    age = request.POST.get("age")
    if request.method == "GET":
        return render(request, "info_add.html")

    
    if user==NULL :
        # return render(request,"info_add.html",'3213')
            return HttpResponse('3213')
    else:
            UserInfo.objects.create(name=user, password=pwd, age=age)# 获取数据
            
   # except models.UserInfo.DoesNotExist:
       #return render(request,"info_add.html",'3213')
        
    

    return redirect("/info_list/")


def info_delete(request):
    nid = request.GET.get('nid')  # 提交方式是GET方式
    UserInfo.objects.filter(id=nid).delete()
    return redirect("/info_list/")

#test
# views.py的myvariable函数
from django.http import HttpResponse, JsonResponse

def myvariable(request, year, month, day):
    return HttpResponse(str(year)+'/'+str(month)+'/'+str(day))

def mydate(request, year, month, day):
    return HttpResponse(str(year)+'/'+str(month)+'/'+str(day))


def book(request):
    return HttpResponse('这是jiangyetest')

def book_detail(request,book_id):
    text = '图书id是 %s'% book_id
    return HttpResponse(text)

def register(request):
    if request.method == 'POST':
        username1 = request.POST.get('user_name')
        pwd = request.POST.get('pwd')
        cpwd = request.POST.get('cpwd')
        email = request.POST.get('email')
        allow=request.POST.get('allow')
        age=request.POST.get('age')
        date=request.POST.get('date')
        time1=request.POST.get('time')
        print(allow)
        #if allow !='on':
         #   return render(request,'register.html',{'errmsg':'huoyigeiwoligiaogiao'})
        uuu=UserInfo.objects.create(name=username1,password=pwd,email=email,age=age,date=date,create_time=time1)
    #userinfov.is_active()=0
        uuu.save()
        #发送邮件
        subject='youjian'
        message="huanying <br> <a href=''dianjijihuo" 
        #res=send_mail(subject=subject,message=message,from_email=settings.EMAIL_HOST_USER,recipient_list=[email,])
        #print(res)

        return render(request,'tpl.html')
    return render(request,'register.html')


    
def check_user(request):
    username = request.GET.get('username')
    user=UserInfo.objects.filter(username=username).first
    

def login():
    return HttpResponse('login')

jiangyeapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>

   
    
</head> 

<body><li>
   这是index
</li>
  

   <input type="button" value="tijiao">

<div>
   
   <a href="/info_list" value="提交" target="_blank" rel="noopener noreferrer" class="btn btn-primary" >tijao
   </a>
<li>
   
  
      <li><a href="/user/register" type="button">register</li>

</li>
<li>
   <a href="testjs/">testjs</a>
</li>

</div>
</body>
</html>

jiangyeapp/templates/superindex.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Carousel Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/carousel/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

<script src="https://cdn.tiny.cloud/1/77cu9iec3wu665q3y1v12jb7yd384z3gt7tjd1p4luqqi1ia/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>


    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


<style>
  body {
  padding-top: 3rem;
  padding-bottom: 3rem;
  color: #5a5a5a;
}


/* CUSTOMIZE THE CAROUSEL
-------------------------------------------------- */

/* Carousel base class */
.carousel {
  margin-bottom: 4rem;
}
/* Since positioning the image, we need to help out the caption */
.carousel-caption {
  bottom: 3rem;
  z-index: 10;
}

/* Declare heights because of positioning of img element */
.carousel-item {
  height: 32rem;
}
.carousel-item > img {
  position: absolute;
  top: 0;
  right: 0;
  min-width: 100%;
  height: 32rem;
}


/* MARKETING CONTENT
-------------------------------------------------- */

/* Center align the text within the three columns below the carousel */
.marketing .col-lg-4 {
  margin-bottom: 1.5rem;
  text-align: center;
}
.marketing h2 {
  font-weight: 400;
}
.marketing .col-lg-4 p {
  margin-right: .75rem;
  margin-left: .75rem;
}


/* Featurettes
------------------------- */

.featurette-divider {
  margin: 5rem 0; /* Space out the Bootstrap <hr> more */
}

/* Thin out the marketing headings */
.featurette-heading {
  font-weight: 300;
  line-height: 1;
}


/* RESPONSIVE CSS
-------------------------------------------------- */

@media (min-width: 40em) {
  /* Bump up size of carousel content */
  .carousel-caption p {
    margin-bottom: 1.25rem;
    font-size: 1.25rem;
    line-height: 1.4;
  }

  .featurette-heading {
    font-size: 50px;
  }
}

@media (min-width: 62em) {
  .featurette-heading {
    margin-top: 7rem;
  }
}

</style>

<style>
  body {
  padding-top: 3rem;
  padding-bottom: 3rem;
  color: #5a5a5a;
}


/* CUSTOMIZE THE CAROUSEL
-------------------------------------------------- */

/* Carousel base class */
.carousel {
  margin-bottom: 4rem;
}
/* Since positioning the image, we need to help out the caption */
.carousel-caption {
  bottom: 3rem;
  z-index: 10;
}

/* Declare heights because of positioning of img element */
.carousel-item {
  height: 32rem;
}
.carousel-item > img {
  position: absolute;
  top: 0;
  left: 0;
  min-width: 100%;
  height: 32rem;
}


/* MARKETING CONTENT
-------------------------------------------------- */

/* Center align the text within the three columns below the carousel */
.marketing .col-lg-4 {
  margin-bottom: 1.5rem;
  text-align: center;
}
.marketing h2 {
  font-weight: 400;
}
/* rtl:begin:ignore */
.marketing .col-lg-4 p {
  margin-right: .75rem;
  margin-left: .75rem;
}
/* rtl:end:ignore */


/* Featurettes
------------------------- */

.featurette-divider {
  margin: 5rem 0; /* Space out the Bootstrap <hr> more */
}

/* Thin out the marketing headings */
.featurette-heading {
  font-weight: 300;
  line-height: 1;
  /* rtl:remove */
  letter-spacing: -.05rem;
}


/* RESPONSIVE CSS
-------------------------------------------------- */

@media (min-width: 40em) {
  /* Bump up size of carousel content */
  .carousel-caption p {
    margin-bottom: 1.25rem;
    font-size: 1.25rem;
    line-height: 1.4;
  }

  .featurette-heading {
    font-size: 50px;
  }
}

@media (min-width: 62em) {
  .featurette-heading {
    margin-top: 7rem;
  }
}

</style>

    
    <!-- Custom styles for this template -->
    <link href="carousel.css" rel="stylesheet">
  </head>
  <body>
    <div>
      {% if user.is_authenticated %}
    
      <a>giaogiaogiao</a>
      <li>
           {{ request.user.username }}
           {{ request.user.email }}
        <img src="{{ MEDIA_URL }}{{ user.userImg}}"+ alt="">
      </li>
    
      <a href="{%url  'user:logout' %}">logout</a>
      {% else %}
      123123
    
      {% endif %}
     </div>
    <script>
      tinymce.init({
        selector: '#mytextarea',
        // 'theme':'advanced',
        plugins: 'image', //使用image插件
        toolbar: 'image', //工具栏显示
        images_upload_url:'media/img',


      });
    </script>

  </head>

  <body>
  <h1>TinyMCE Quick Start Guide</h1>
    <form action="{% url 'post' %}" method="post">
      {% csrf_token%}
      <p><input type="number" name="save_number" value="0" placeholder="number"></p>
     

      <p><input type="text" name="title" placeholder="inputyouidea"></p>
<p>
        <textarea id="mytextarea" name="context">Hello, World!</textarea>
      </p>
      
      <p><input type="submit" value="publish"></p>
    </form>
    
    {% if error %}
                    <div>{{ error }}</div>
                {% endif %}




















    
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Carousel</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
</header>

<main>

  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-start">
            <h1>test1</h1>
            <p>test2</p>
            <p><a class="btn btn-lg btn-primary" href="#">Sign up today</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption">
            <h1>test3</h1>
            <p>test4</p>
            <p><a class="btn btn-lg btn-primary" href="#">Learn more</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <svg class="bd-placeholder-img" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false"><rect width="100%" height="100%" fill="#777"/></svg>

        <div class="container">
          <div class="carousel-caption text-end">
            <h1>test5</h1>
            <p>test6</p>
            <p><a class="btn btn-lg btn-primary" href="#">test7</a></p>
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">test8</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>




    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">test0 <span class="text-muted">test1</span></h2>
        <p class="lead">test2</p>
        <p class="lead">test3</p>
        <p class="lead">test2</p>
        <p class="lead">test3</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">testimg</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading">testq <span class="text-muted">testw</span></h2>
        <p class="lead">testc</p>
      </div>
      <div class="col-md-5 order-md-1">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
        <p class="lead">And yes, this is the last block of representative placeholder content. Again, not really intended to be actually read, simply here to give you a better view of what this would look like with some actual content. Your content.</p>
      </div>
      <div class="col-md-5">
        <svg class="bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="500" height="500" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#eee"/><text x="50%" y="50%" fill="#aaa" dy=".3em">500x500</text></svg>

      </div>
    </div>

    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2017–2021 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>


    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

      
  </body>
</html>